### PR TITLE
Change dependencies compile to implementation for Gradle 7+

### PR DESCRIPTION
**Pull request by YannikS14**
With Gradle version 7 or higher, compile is no longer supported and needs to be changed into implementation.

### CODE REVIEW

**Review by veleasb — APPROVED** [review]

**Review by veleasb — APPROVED** [review]

**Comment by Dwikavindra** [comment]
@suraneti could you please publish the new version of this repo to npm?

**Comment by manage-some** [comment]
Can you please approve this PR?

**Comment by kolucciy** [comment]
Any update on this?

**Comment by suraneti** [comment]
Apologies for the late merge, my primary work kept me busy, and I didn't have the time to review this repository earlier.

**Pull request merged**
